In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.5.2


In [4]:
# Array Creation and Dimensions :

# NumPy array / ndarray
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

# 0-D array
arr_0d = np.array(42)
print("\n0-D array:", arr_0d)
print("Dimensions:", arr_0d.ndim)

# 1-D array
arr_1d = np.array([1, 2, 3, 4, 5])
print("\n1-D array:", arr_1d)
print("Dimensions:", arr_1d.ndim)

# 2-D array
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("\n2-D array:\n", arr_2d)
print("Dimensions:", arr_2d.ndim)

# 3-D array
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print("\n3-D array:\n", arr_3d)
print("Dimensions:", arr_3d.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>

0-D array: 42
Dimensions: 0

1-D array: [1 2 3 4 5]
Dimensions: 1

2-D array:
 [[1 2 3]
 [4 5 6]]
Dimensions: 2

3-D array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimensions: 3


In [5]:
# Array Indexing:

# 1-D array indexing
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])      # First element
print(arr[1])      # Second element
print(arr[-1])     # Last element
print(arr[1] + arr[3])  # 20 + 40

10
20
50
60


In [6]:
# 2-D array indexing
arr_2d = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr_2d[0, 0])   # Row 0, column 0 -> 10
print(arr_2d[0, 1])   # Row 0, column 1 -> 20
print(arr_2d[1, 2])   # Row 1, column 2 -> 60
print(arr_2d[1, -1])  # Last item of second row -> 60

10
20
60
60


In [7]:
# 3-D array indexing
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print(arr_3d[0, 0, 0])  # 1
print(arr_3d[0, 1, 2])  # 6
print(arr_3d[1, 0, 1])  # 8
print(arr_3d[1, 1, 2])  # 12

1
6
8
12


In [8]:
# Array Slicing :

# 1-D array slicing
arr = np.array([10, 20, 30, 40, 50, 60, 70])

print(arr[1:5])     # Index 1 to 4
print(arr[4:])      # Index 4 to end
print(arr[:4])      # Beginning to index 3
print(arr[-3:-1])   # Negative indexes
print(arr[::2])     # Every second element
print(arr[1:6:2])   # Start, stop, step

[20 30 40 50]
[50 60 70]
[10 20 30 40]
[50 60]
[10 30 50 70]
[20 40 60]


In [9]:
# 2-D array slicing
arr_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# From second row, get elements at index 1 and 2
print(arr_2d[1, 1:3])

# From all rows, get second and third columns
print(arr_2d[:, 1:3])

# From row 1 onwards, get columns 1 to 2
print(arr_2d[1:, 1:3])

# First column from every row
print(arr_2d[:, 0])

# Every alternate row and column
print(arr_2d[::2, ::2])

[6 7]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[ 6  7]
 [10 11]]
[1 5 9]
[[ 1  3]
 [ 9 11]]


In [11]:
#Shape and Reshape

arr = np.array([1, 2, 3, 4, 5, 6])

# Array shape
print(arr.shape)

# Reshape 1-D array to 2 rows and 3 columns
reshaped_2x3 = arr.reshape(2, 3)
print(reshaped_2x3)
print(reshaped_2x3.shape)

# Reshape to 3 rows and 2 columns
reshaped_3x2 = arr.reshape(3, 2)
print(reshaped_3x2)

# Let NumPy calculate one dimension using -1
print(arr.reshape(2, -1))
print(arr.reshape(-1, 2))

# Convert 2-D array back to 1-D
print(reshaped_2x3.reshape(-1))

# Flatten the array
print(reshaped_2x3.flatten())

(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [12]:
#Joining Arrays

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Join arrays using concatenate
joined = np.concatenate((arr1, arr2))
print(joined)

# Stack arrays vertically
vertical_stack = np.vstack((arr1, arr2))
print(vertical_stack)

# Stack arrays horizontally
horizontal_stack = np.hstack((arr1, arr2))
print(horizontal_stack)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [14]:
arr1_2d = np.array([
    [1, 2],
    [3, 4]
])

arr2_2d = np.array([
    [5, 6],
    [7, 8]
])

# Join row-wise (axis=0)
print(np.concatenate((arr1_2d, arr2_2d), axis=0))

# Join column-wise (axis=1)
print(np.concatenate((arr1_2d, arr2_2d), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [15]:
# Zeros, Ones, and Full

# Array filled with zeros
print(np.zeros(5))
print(np.zeros((2, 3)))
print(np.zeros((2, 3), dtype=int))

# Array filled with ones
print(np.ones(5))
print(np.ones((2, 3)))
print(np.ones((2, 3), dtype=int))

# Array filled with a specified value
print(np.full(5, 7))
print(np.full((2, 3), 9))

# Identity matrix
print(np.eye(3))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]
[7 7 7 7 7]
[[9 9 9]
 [9 9 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# Numbers from 0 to 4
print(np.arange(5))

# Numbers from 1 to 9
print(np.arange(1, 10))

# Numbers from 1 to 9 with step size 2
print(np.arange(1, 10, 2))

# Even numbers
print(np.arange(0, 20, 2))

# Decimal sequence
print(np.arange(0, 1, 0.1))

[0 1 2 3 4]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [17]:
#Mathematical Manipulation

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Element-wise arithmetic
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 ** 2)

# Scalar operations
print(arr1 + 10)
print(arr1 * 2)
print(arr1 / 2)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]
[11 12 13 14]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [18]:
arr = np.array([10, 20, 30, 40, 50])

# Statistical operations
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Standard deviation:", np.std(arr))
print("Variance:", np.var(arr))

Sum: 150
Mean: 30.0
Minimum: 10
Maximum: 50
Standard deviation: 14.142135623730951
Variance: 200.0
